"""First migration

Revision ID: b7fa85a0f641
Revises: 
Create Date: 2021-03-28 19:14:23.741480

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7fa85a0f641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address_from', sa.String(length=16), nullable=False),
                    sa.Column('address_to', sa.String(length=16), nullable=False),
                    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(length=16), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transactions')
    # ### end Alembic commands ###
