export const GET_USERS = "TRANSACTIONS/GET_USERS"
export const CREATE_USER = "TRANSACTIONS/CREATE_USER"

export const GET_TRANSACTIONS = "TRANSACTIONS/GET_TRANSACTIONS"
export const CREATE_TRANSACTION = "TRANSACTIONS/CREATE_TRANSACTION"
